---
title: "🛡️ Reliable"
subtitle: "Build trust in your code through testing, automation, and reproducible environments"
format:
  html:
    toc: true
---

## Overview

Making code _reliable_ means ensuring it does what you think it does, and that it keeps doing so even as your data or dependencies change. In this session, you'll learn to test your code, automate quality checks, and set up your environment so anyone can reproduce your results.

## 🎯 Learning objectives

By the end of this session, you should be able to:

- Write simple unit tests and understand why testing matters
- Handle environment variables and secrets securely
- Understand what CI/CD is and how automated testing can be incorporated into a workflow
- Understand the purpose of virtual environments such as {renv} and venv


## 📖 Before the session

Please complete the [pre-learning materials](pre-learning.qmd). These typically take 60 – 90 minutes and are essential for getting the most out of the session. Share your answers, examples and any questions in the shared learning document for your group. 

- [Group 1](https://nhs-my.sharepoint.com/:w:/r/personal/rhian_davies25_nhs_net/Documents/SCIC%20RAP%20Accelerator/RAP%20Accelerator%20Group%201.docx?d=w5a54954b949d458d80fa7eeb11875f98&csf=1&web=1&e=FZvj3e)
- [Group 2](https://nhs-my.sharepoint.com/:w:/r/personal/rhian_davies25_nhs_net/Documents/SCIC%20RAP%20Accelerator/RAP%20Accelerator%20Group%202.docx?d=w5dd12e7ea9d8485994e722491950da36&csf=1&web=1&e=IUOVmP)
- [Group 3](https://nhs-my.sharepoint.com/:w:/r/personal/rhian_davies25_nhs_net/Documents/SCIC%20RAP%20Accelerator/RAP%20Accelerator%20Group%203.docx?d=w85db45aa7bc340c08c23087965059fa0&csf=1&web=1&e=FOXxEP)
- [Group 4](https://nhs-my.sharepoint.com/:w:/r/personal/rhian_davies25_nhs_net/Documents/SCIC%20RAP%20Accelerator/RAP%20Accelerator%20Group%204.docx?d=waef817406959496e821355fed6bd485b&csf=1&web=1&e=1uRrVI)