project:
  type: website

website:
  title: "RAP Flipped Classroom"
  navbar:
    left:
      - about.qmd
      - learning_materials/index.qmd

format:
  html:
    theme:
      light:
        - brand
      dark:
        - brand
    css:
      - _SUBrand.StyleSheet.css
    toc: true



